#ifndef _DEFS_H
#define _DEFS_H

// Every header file included shall be self-dependent to keep 
// away from "undefined errors" generated by the complier.
// In principle, all the headers should be independent,
// so they can be organized in any order within the including
// queue. However, frankly, that's hard to achieve without proper
// using of #include directive inside the header file itself.

#include "types.h"
#include "x86.h"
#include "kbd.h"
#include "ide.h"
#include "console.h"
#include "memory.h"
#include "pic.h"
#include "trap.h"
#include "timer.h"
#include "proc.h"

// Global Functions & Variables

// trapasm.S
extern uint vectors[];

// trap.c
extern void trap_init(void);
extern void trap(struct trapframe *);

// pic.c
extern void pic_init(void);
extern void pic_enable_irq(uchar);
extern void pic_send_eoi(uchar);

// console.c
extern void console_init(void);
extern void cprintf(const void *, int);
extern void console_intr(int);

// ide.c
extern void ide_init(void);
extern void ide_intr(void);
extern struct ide_buf *ide_bget(uint, uint, uint);
extern void ide_brelse(struct ide_buf *);

// timer.c
extern void timer_init(void);

// kbd.c
extern void kbd_init(void);
extern int kbdgetc(void);
extern void kbd_intr(void);

// vm.c
extern void kvm_init(void);
extern void pgalloc_init(void);
extern void page_free(uint);
extern uint page_alloc(void);
extern void kvm_setup(struct pte *);

// panic.c
extern void panic(const char *);

#endif
